<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <WarningsAsErrors>CS1591</WarningsAsErrors>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>

    <Authors>Akintunde Morakinyo</Authors>
    <Company>Akintunde Morakinyo</Company>
    <Copyright>Copyright © Akintunde Morakinyo</Copyright>

    <Version>0.1.1</Version>

    <RepositoryUrl>https://github.com/akin2unde/SimpleORM.Net</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/akin2unde/SimpleORM.Net</PackageProjectUrl>

    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageReadmeFile>README.md</PackageReadmeFile>

    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup Condition="'$(IsPackable)' == 'true'">
    <None
      Include="$(MSBuildThisFileDirectory)README.md"
      Pack="true"
      PackagePath="\"
      Visible="false" />
  </ItemGroup>
</Project>