<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup><IsPackable>false</IsPackable></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/SimpleORM.Net/SimpleORM.Net.csproj"/>
    <ProjectReference Include="../../src/SimpleORM.Net.SqlServer/SimpleORM.Net.SqlServer.csproj"/>
    <ProjectReference Include="../../src/SimpleORM.Net.MongoDB/SimpleORM.Net.MongoDB.csproj"/>
    <ProjectReference Include="../../src/SimpleORM.Net.AspNetCore/SimpleORM.Net.AspNetCore.csproj"/>
  </ItemGroup>
</Project>
