<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
  <IsPackable>true</IsPackable>
  <PackageId>SimpleORM.Net.AspNetCore</PackageId>
  <Description>ASP.NET Core integration for SimpleORM.Net.</Description>
  </PropertyGroup>
  <ItemGroup>
  <ProjectReference Include="../SimpleORM.Net/SimpleORM.Net.csproj"/>
  <FrameworkReference Include="Microsoft.AspNetCore.App"/>
  </ItemGroup>
</Project>
