using System.Dynamic;

using System.Text.Json;

using Microsoft.Extensions.DependencyInjection;

using MongoDB.Bson;

using MongoDB.Driver;

using SimpleORM.Net.Abstractions;

using SimpleORM.Net.Configuration;

using SimpleORM.Net.Metadata;

using SimpleORM.Net.Models;

using SimpleORM.Net.Query;

namespace SimpleORM.Net.MongoDB;

/// <summary>MongoDB provider.</summary>
public sealed class MongoDatabaseProvider : IDatabaseProvider, IDBQuery
{

    private readonly SimpleOrmOptions _o;

    private readonly IDBMetadataProvider _m;

    private readonly ITenantProvider _t;

    private readonly IMongoClient _client;

    private readonly IMongoDatabase _db;

    /// <summary>Creates provider.</summary>
    public MongoDatabaseProvider(SimpleOrmOptions o, IDBMetadataProvider m, ITenantProvider t)
    {
        _o = o;

        _m = m;

        _t = t;

        var c = o.Connection;

        var cs = string.IsNullOrWhiteSpace(c.Username) ? $"mongodb://{c.Host}:{c.Port}" : $"mongodb://{Uri.EscapeDataString(c.Username)}:{Uri.EscapeDataString(c.Password ?? "")}@{c.Host}:{c.Port}/{c.Database}";

        _client = new MongoClient(cs);

        _db = _client.GetDatabase(c.Database);

    }

    /// <inheritdoc />
    public async Task<IDBTransaction> BeginTransaction(CancellationToken ct = default)
    {
        var s = await _client.StartSessionAsync(cancellationToken: ct);

        s.StartTransaction();

        return new MongoTx(s);

    }

    /// <inheritdoc />
    public async Task<T?> SelectSingle<T>(SearchParam p, CancellationToken ct = default) where T : DBModel => await Col<T>().Find(Filter<T>(p)).Sort(Sort<T>(p)).Limit(1).FirstOrDefaultAsync(ct);

    /// <inheritdoc />
    public Task<T?> GetByCode<T>(string code, CancellationToken ct = default) where T : DBModel
    {
        var p = new SearchParam();

        p.Filters.Add(new SearchFilter
        {
            Field = nameof(DBModel.Code),
            Operator = SearchOperator.Equal,
            Value = code
        }
        );

        return SelectSingle<T>(p, ct);

    }

    /// <inheritdoc />
    public async Task<IReadOnlyList<T>> Select<T>(SearchParam p, int skip, int limit, CancellationToken ct = default) where T : DBModel => await Col<T>().Find(Filter<T>(p)).Sort(Sort<T>(p)).Skip(skip).Limit(limit).ToListAsync(ct);

    /// <inheritdoc />
    public Task<long> Count<T>(SearchParam p, CancellationToken ct = default) where T : DBModel => Col<T>().CountDocumentsAsync(Filter<T>(p), cancellationToken: ct);

    /// <inheritdoc />
    public Task Insert<T>(IReadOnlyList<T> x, IDBTransaction tr, CancellationToken ct = default) where T : DBModel => Col<T>().InsertManyAsync(As(tr).Session, x, cancellationToken: ct);

    /// <inheritdoc />
    public async Task Update<T>(IReadOnlyList<T> x, IDBTransaction tr, CancellationToken ct = default) where T : DBModel
    {
        var w = x.Select(v => new ReplaceOneModel<T>(Scoped<T>(Builders<T>.Filter.Eq(y => y.Code, v.Code), false), v)).Cast<WriteModel<T>>().ToArray();

        if (w.Length > 0) await Col<T>().BulkWriteAsync(As(tr).Session, w, cancellationToken: ct);

    }

    /// <inheritdoc />
    public async Task Delete<T>(IReadOnlyList<T> x, bool hard, IDBTransaction tr, CancellationToken ct = default) where T : DBModel
    {
        if (hard) await Col<T>().DeleteManyAsync(As(tr).Session, Scoped<T>(Builders<T>.Filter.In(y => y.Code, x.Select(y => y.Code)), false), cancellationToken: ct);

        else
        {
            var w = x.Select(v => new UpdateOneModel<T>(Scoped<T>(Builders<T>.Filter.Eq(y => y.Code, v.Code), false), Builders<T>.Update.Set(y => y.DeletedAt, v.DeletedAt ?? DateTime.UtcNow).Set(y => y.UpdatedAt, v.UpdatedAt).Set(y => y.UpdatedBy, v.UpdatedBy))).Cast<WriteModel<T>>().ToArray();

            if (w.Length > 0) await Col<T>().BulkWriteAsync(As(tr).Session, w, cancellationToken: ct);

        }
    }

    /// <inheritdoc />
    public string GenerateDebugQuery<T>(SearchParam p, int skip = 0, int limit = 100) where T : DBModel => JsonSerializer.Serialize(new
    {
        collection = _m.GetMetadata<T>().TableName,
        skip,
        limit,
        note = "MongoDB filter is generated by provider at execution time."
    }
    , new JsonSerializerOptions
    {
        WriteIndented = true
    }
    );

    /// <inheritdoc />
    public async Task<dynamic?> QuerySingle(string q, object? p = null, CancellationToken ct = default) => (await Query(q, p, ct)).FirstOrDefault();

    /// <inheritdoc />
    public async Task<IReadOnlyList<dynamic>> Query(string q, object? p = null, CancellationToken ct = default)
    {
        var d = BsonDocument.Parse(q);

        var c = _db.GetCollection<BsonDocument>(d["collection"].AsString);

        var f = d.TryGetValue("filter", out var v) ? v.AsBsonDocument : new BsonDocument();

        var r = await c.Find(f).ToListAsync(ct);

        return r.Select(x => (dynamic)JsonSerializer.Deserialize<ExpandoObject>(x.ToJson())!).ToArray();

    }

    /// <inheritdoc />
    public Task<T?> QuerySingle<T>(string q, object? p = null, CancellationToken ct = default) => throw new NotSupportedException("Use dynamic raw Mongo query in MVP or IDataRepository.");

    /// <inheritdoc />
    public Task<IReadOnlyList<T>> Query<T>(string q, object? p = null, CancellationToken ct = default) => throw new NotSupportedException("Use dynamic raw Mongo query in MVP or IDataRepository.");

    /// <inheritdoc />
    public Task<long> Execute(string q, object? p = null, CancellationToken ct = default) => throw new NotSupportedException("Mongo raw Execute is not generalized in MVP.");

    internal IMongoDatabase Database => _db;

    private IMongoCollection<T> Col<T>() where T : DBModel => _db.GetCollection<T>(_m.GetMetadata<T>().TableName);

    private FilterDefinition<T> Filter<T>(SearchParam p) where T : DBModel
    {
        var b = Builders<T>.Filter;

        var fs = new List<FilterDefinition<T>>();

        var m = _m.GetMetadata<T>();

        foreach (var x in p.Filters)
        {
            var c = m.Columns.First(z => z.PropertyName.Equals(x.Field, StringComparison.OrdinalIgnoreCase));

            fs.Add(x.Operator switch
            {
                SearchOperator.Equal => b.Eq(c.ColumnName, x.Value),
                SearchOperator.NotEqual => b.Ne(c.ColumnName, x.Value),
                SearchOperator.Contains => b.Regex(c.ColumnName, new BsonRegularExpression(System.Text.RegularExpressions.Regex.Escape(x.Value?.ToString() ?? ""), "i")),
                SearchOperator.In => b.In(c.ColumnName, ((System.Collections.IEnumerable)x.Value!).Cast<object?>()),
                _ => throw new NotSupportedException($"Operator {x.Operator} not implemented in Mongo MVP.")
            }
            );

        }
        if (!string.IsNullOrWhiteSpace(p.Search))
        {
            var ors = m.SearchableColumns.Select(c => (FilterDefinition<T>)b.Regex(c.ColumnName, new BsonRegularExpression(System.Text.RegularExpressions.Regex.Escape(p.Search), "i"))).ToArray();

            if (ors.Length > 0) fs.Add(b.Or(ors));

        }
        var basef = fs.Count == 0 ? b.Empty : (p.Condition == SearchCondition.Or ? b.Or(fs) : b.And(fs));

        return Scoped<T>(basef, p.IncludeDeleted);

    }

    private FilterDefinition<T> Scoped<T>(FilterDefinition<T> f, bool includeDeleted) where T : DBModel
    {
        var b = Builders<T>.Filter;

        var all = new List<FilterDefinition<T>>
        {
            f
        }
        ;

        if (_o.MultiTenancy.Enabled) all.Add(b.Eq(x => x.Tenant, _t.GetTenant() ?? throw new InvalidOperationException("Tenant required.")));

        if (!_m.GetMetadata<T>().HardDelete && !includeDeleted) all.Add(b.Eq(x => x.DeletedAt, null));

        return b.And(all);

    }

    private SortDefinition<T> Sort<T>(SearchParam p) where T : DBModel
    {
        var b = Builders<T>.Sort;

        var m = _m.GetMetadata<T>();

        var x = p.OrderBy.Select(o => o.Descending ? b.Descending(m.Columns.First(c => c.PropertyName == o.Field).ColumnName) : b.Ascending(m.Columns.First(c => c.PropertyName == o.Field).ColumnName)).ToList();

        x.Add(b.Ascending(nameof(DBModel.Code)));

        return b.Combine(x);

    }

    private static MongoTx As(IDBTransaction t) => t as MongoTx ?? throw new InvalidOperationException("Wrong provider transaction.");

}
