<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><IsPackable>true</IsPackable>
  <PackageId>SimpleORM.Net.MongoDB</PackageId>
  <Description>MongoDB provider for SimpleORM.Net.</Description>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../SimpleORM.Net/SimpleORM.Net.csproj"/>
  <PackageReference Include="MongoDB.Driver"/></ItemGroup>
</Project>
